# Generated by Django 5.1.4 on 2024-12-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='email_address',
        ),
        migrations.AlterField(
            model_name='student',
            name='course_ending_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='student',
            name='course_starting_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='experience',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_tagline',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.CharField(max_length=1000),
        ),
    ]
