# Generated by Django 5.1.4 on 2024-12-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0002_remove_student_email_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_summary',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
