# Generated by Django 5.1.4 on 2024-12-19 14:37

import django.db.models.deletion
import swawlambi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0006_alter_department_head_of_department_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('desc', models.CharField(blank=True, max_length=500, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('image', models.FileField(default=None, max_length=250, null=True, upload_to='product_image', validators=[swawlambi_app.models.validate_file_size])),
                ('enabled', models.BooleanField(default=True, null=True)),
                ('is_approved', models.BooleanField(default=False, null=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swawlambi_app.department')),
            ],
        ),
    ]
