# Generated by Django 5.1.4 on 2025-01-12 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0008_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
