# Generated by Django 5.1.4 on 2025-01-20 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0009_product_is_rejected_service_is_rejected'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=200)),
                ('job_description', models.TextField()),
                ('job_location', models.CharField(max_length=200)),
                ('job_type', models.CharField(max_length=200)),
                ('job_experience', models.CharField(max_length=200)),
                ('job_salary', models.CharField(max_length=200)),
                ('job_skills', models.CharField(max_length=200)),
                ('job_posted_on', models.DateField(auto_now_add=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('active', models.BooleanField(default=True)),
                ('recruiter_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swawlambi_app.recruiter')),
            ],
            options={
                'verbose_name_plural': 'Jobs',
            },
        ),
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_status', models.CharField(default='Applied', max_length=200)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swawlambi_app.student')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swawlambi_app.job')),
            ],
            options={
                'verbose_name_plural': 'Applications',
            },
        ),
    ]
