# Generated by Django 5.1.4 on 2025-01-21 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0011_department_phone_number_recruiter_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='github',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='linkedin',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='resume',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='website',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
