# Generated by Django 5.1.4 on 2025-01-21 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0013_alter_department_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='phone_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
