# Generated by Django 5.1.4 on 2025-01-21 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0015_remove_student_branch_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='branch_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
