# Generated by Django 5.1.4 on 2025-01-21 13:23

import autoslug.fields
import django.db.models.deletion
import swawlambi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0016_student_branch_name_student_course_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='name', unique=True)),
                ('pagination_flag', models.BooleanField(default=True)),
                ('preview_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'notices types',
                'db_table': 'notices types',
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('notice_date', models.DateField(null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('enabled', models.BooleanField(null=True)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', 'Image'), ('word', 'Word'), ('excel', 'Excel'), ('link', 'Link')], max_length=100, null=True)),
                ('file', models.FileField(default=None, max_length=250, null=True, upload_to=swawlambi_app.models.notice_file_upload_path, validators=[swawlambi_app.models.validate_file_size])),
                ('show_in_notices', models.BooleanField(null=True)),
                ('last_date_display', models.DateField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('dept_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='swawlambi_app.department')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='swawlambi_app.noticetype')),
            ],
            options={
                'verbose_name_plural': 'notices',
                'db_table': 'notices',
            },
        ),
    ]
