# Generated by Django 5.1.4 on 2025-01-22 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0017_noticetype_notice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='active',
        ),
        migrations.AddField(
            model_name='job',
            name='enabled',
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_rejected',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
