# Generated by Django 5.1.4 on 2025-01-22 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0018_remove_job_active_job_enabled_job_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='recruiter_name',
            new_name='recruiter',
        ),
    ]
