# Generated by Django 5.1.4 on 2025-03-05 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0019_rename_recruiter_name_job_recruiter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notice',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='dept_name',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='file_type',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='last_date_display',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='show_in_notices',
        ),
        migrations.RemoveField(
            model_name='notice',
            name='url',
        ),
    ]
