# Generated by Django 5.1.4 on 2025-03-07 02:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0020_remove_notice_created_by_remove_notice_created_on_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='noticetype',
            name='pagination_flag',
        ),
        migrations.RemoveField(
            model_name='noticetype',
            name='preview_url',
        ),
    ]
