# Generated by Django 5.1.4 on 2025-03-11 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0021_remove_noticetype_pagination_flag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='product',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='department',
            name='concerened_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='amazon_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flipkart_link',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
