# Generated by Django 5.1.4 on 2025-03-15 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0022_remove_product_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recruiter',
            old_name='phone_number',
            new_name='company_phone_number',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='service',
            name='is_rejected',
        ),
        migrations.AddField(
            model_name='recruiter',
            name='hr_mail',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='hr_mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='hr_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='industry_type',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
