# Generated by Django 5.1.4 on 2025-03-15 04:47

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0024_remove_recruiter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='hr_mail',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='hr_mobile',
            field=models.IntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='hr_name',
            field=models.CharField(default=datetime.datetime(2025, 3, 15, 4, 47, 52, 874558, tzinfo=datetime.timezone.utc), max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='industry_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
