# Generated by Django 5.1.4 on 2025-03-20 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0024_remove_recruiter_industry_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recruiter',
            name='company_phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
