# Generated by Django 5.1.4 on 2025-03-26 12:55

import swawlambi_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0025_alter_recruiter_company_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='file',
            field=models.FileField(blank=True, default=None, max_length=250, null=True, upload_to=swawlambi_app.models.notice_file_upload_path, validators=[swawlambi_app.models.validate_file_size]),
        ),
    ]
