# Generated by Django 5.1.4 on 2025-03-28 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0027_callbackrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=10),
        ),
    ]
