# Generated by Django 5.1.4 on 2025-03-29 02:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0028_callbackrequest_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swawlambi_app.department'),
        ),
        migrations.AlterField(
            model_name='service',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='swawlambi_app.department'),
        ),
    ]
