# Generated by Django 5.1.4 on 2025-03-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0032_remove_job_contact_email_alter_recruiter_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
