# Generated by Django 5.1.4 on 2025-04-06 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swawlambi_app', '0037_remove_admin_details_mail'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruiter',
            name='first_login',
            field=models.BooleanField(default=True),
        ),
    ]
